### PR TITLE
Add ERB support

### PR DESCRIPTION
**Pull request by clm-a**
For those awkward guys that still do some Ruby.

### CODE REVIEW

**Comment by vinkla** [comment]
Haha, I understand. I currently don't have any time to work on this but I'll leave this open as a feature request. You're welcome to send a pull request.

**Comment by phillipspc** [comment]
hey now. nothing awkward about using Ruby 😉 
@vinkla This seems to work fine for me, would love to see this merged.

**Comment by vinkla** [comment]
> @vinkla This seems to work fine for me, would love to see this merged.

This isn't a pull request. Are you saying Ruby is already supported?

**Comment by phillipspc** [comment]
@vinkla Looks like a pull request to me? And when I make the change locally that is shown here, it works.

**Comment by vinkla** [comment]
Oh, you're right. I was confused by the notification system.

**Comment by vinkla** [comment]
Thanks @clm-a and @phillipspc!

**Pull request merged**
